language: python
python:
- '3.7'
addons:
  ssh_known_hosts: $MAIN_DEPLOY_HOST
before_script:
- export tag=${TRAVIS_COMMIT:0:7}
- pip install -r requirements.txt
- python validate.py
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- python build_apps.py $tag
before_deploy:
- openssl aes-256-cbc -K $encrypted_50cd93b296f8_key -iv $encrypted_50cd93b296f8_iv
  -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: python deploy.py $tag
  on:
    branch: master
before_install:

