apps:
- author: bill
  deploy: false
  description: description placeholder
  framework: flask
  host: localhost
  memory: 256
  name: test-app
  port: 8001
  sub_domain: test-app
port: 8000
store_version: 0.0.1
